### ISSUE TITLE
When changing levels, can't move around menu

### ISSUE THREAD

**Issue by c07841c** [l010423c/TGP_Game2#13]
Action: Select level 2, then try to select any other level.
Expected result: Select level 1 or 3
Result: Nothing happens
Frequency: 100%

**Comment by c07841c** [comment]
![image](https://cloud.githubusercontent.com/assets/8998040/7140836/90e96186-e2c5-11e4-8899-d289c65daea3.png)

**Comment by Leeton** [comment]
Works fine if you click and drag left or right.

**Comment by l010423c** [comment]
This has not been added in. Buttons on sides removed.
